# Generated by Django 3.1.6 on 2021-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0002_a_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='b',
            name='age',
            field=models.IntegerField(default=990),
        ),
    ]
