# Generated by Django 3.1.6 on 2021-02-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=16)),
                ('catalog', models.CharField(max_length=64)),
                ('vender', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=128)),
            ],
        ),
    ]
