# Generated by Django 3.1.6 on 2021-02-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0002_excel_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaJiXingNengCanShu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.CharField(max_length=16)),
                ('r_max', models.CharField(max_length=16)),
                ('c_max', models.CharField(max_length=16)),
                ('n_25', models.CharField(max_length=16)),
                ('n_30', models.CharField(max_length=16)),
                ('n_35', models.CharField(max_length=16)),
                ('n_40', models.CharField(max_length=16)),
                ('n_45', models.CharField(max_length=16)),
                ('n_50', models.CharField(max_length=16)),
                ('n_55', models.CharField(max_length=16)),
                ('n_60', models.CharField(max_length=16)),
                ('n_65', models.CharField(max_length=16)),
                ('n_70', models.CharField(max_length=16)),
                ('excel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tower.excel')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tower.sheet')),
            ],
        ),
    ]
